import { button, element, humanize } from "./dom.js";

export function badge(value, tone = null) {
  const key = tone ?? String(value).toLowerCase().replaceAll("_", "-");
  return element("span", { className: `badge badge--${key}`, text: humanize(value) });
}
export function alertBox(message, kind = "info") { return element("div", { className: `alert alert--${kind}`, attributes: { role: kind === "danger" ? "alert" : "status" } }, [element("span", { className: "alert__symbol", text: kind === "danger" ? "!" : "i", attributes: { "aria-hidden": "true" } }), element("p", { text: message })]); }
export function loadingState(title = "Loading") { return element("section", { className: "route-state", attributes: { "aria-busy": "true" } }, [element("span", { className: "spinner", attributes: { "aria-hidden": "true" } }), element("h1", { text: title }), element("p", { text: "Retrieving current server state." })]); }
export function emptyState(title, message, symbol = "◇") { return element("section", { className: "route-state" }, [element("span", { className: "route-state__symbol", text: symbol, attributes: { "aria-hidden": "true" } }), element("h2", { text: title }), element("p", { text: message })]); }
export function errorState(title, message, retry) { const children = [element("span", { className: "route-state__symbol", text: "!", attributes: { "aria-hidden": "true" } }), element("h1", { text: title }), element("p", { text: message })]; if (retry) { const action = button("Try again", "button button--primary"); action.addEventListener("click", retry); children.push(action); } return element("section", { className: "route-state", attributes: { role: "alert" } }, children); }
export function permissionState() { return emptyState("Permission required", "Your authenticated account is not authorized to view rich system diagnostics.", "⊘"); }
export function progress(percent, label) { const safe = Math.max(0, Math.min(100, Number(percent) || 0)); return element("div", { className: "progress" }, [element("div", { className: "progress__track", attributes: { role: "progressbar", "aria-valuemin": "0", "aria-valuemax": "100", "aria-valuenow": safe, "aria-label": label } }, element("div", { className: "progress__bar", attributes: { style: `width: ${safe}%` } })), element("span", { className: "progress__label", text: `${safe}% · ${label}` })]); }
export function pageHeader(title, description, actions = []) { return element("header", { className: "page-header" }, [element("div", {}, [element("h1", { text: title }), element("p", { text: description })]), actions.length ? element("div", { className: "action-row" }, actions) : null]); }
export function card(title, content, options = {}) { const cardNode = element("section", { className: `card ${options.className ?? ""}`.trim() }); const heading = element(options.headingLevel ?? "h2", { text: title }); cardNode.append(element("div", { className: "card__header" }, [element("div", {}, [options.kicker ? element("p", { className: "card__kicker", text: options.kicker }) : null, heading]), options.trailing ?? null])); cardNode.append(content); return cardNode; }
export function metricCard(label, value, meta) { return element("article", { className: "card metric-card" }, [element("p", { className: "metric-card__label", text: label }), element("p", { className: "metric-card__value", text: value }), element("p", { className: "metric-card__meta", text: meta })]); }
